version: "3"

services:
  # django-aws-backend:
  #   image: "133718221787.dkr.ecr.eu-west-1.amazonaws.com/django-aws-backend:latest"
  #   container_name: "django-aws-backend"
  #   command: "gunicorn -b 0.0.0.0:8000 django_aws.wsgi:application"
  #   ports:
  #     - "8000:8000"
  #   restart: "always"

  postgres:
    image: "postgres:14"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "django_aws"

  sqs:
    image: "softwaremill/elasticmq-native:latest"
    ports:
      - "9324:9324"
      - "9325:9325"